### ISSUE TITLE
Custom library

### ISSUE THREAD

**Issue by isulovsky** [fronterapp/thesis-FloatingTurbine#3]
Hi Pere,

First of all, thank you for this contribution. I think it is quite significant for those dealing with FOWT.

I am trying to implement something similar but to a custom solidBodyMotionFunction that also inherits values from the sixDoF library.
I have implemented the same changes as you have in the sixDoFRigidBodyMotion library with createDict and updateDict. However, in my custom library, values from sixDoF are not properly read. When I want to print the values from my library they are always zero.

Please be aware that I am not very advanced in C++ so that is my main problem. Would you be so kind to review the C and H files? I think it should be something trivial but I cannot understand what is the issue. The main difference from yours is that in my library I don't have access to mesh.time(). Maybe that's worth mentioning.

Kind regards and thanks in advance

Ivan

[solidBodyMotionAppendageC.txt](https://github.com/fronterapp/thesis-FloatingTurbine/files/13452371/solidBodyMotionAppendageC.txt)
[solidBodyMotionAppendageH.txt](https://github.com/fronterapp/thesis-FloatingTurbine/files/13452372/solidBodyMotionAppendageH.txt)

**Comment by fronterapp** [comment]
Hello Ivan,

Thanks for the compliment! But I'm afraid I am not advanced in C++ either, and it has been a while since I wrapped up this project. It would be easier if you could further explain the expected vs. actual behaviour of your library, or share the tests you have performed so far.

Best,
Pere

**Comment by isulovsky** [comment]
Pere,

Unfortunately, I cannot share the tests since the STL files are under NDA at the moment. But I don't think the test itself is neccessary. So basically , I am trying to rewrite the rotatingMotion so that the axis and origin are updated accordingly to the sixDoF motion of the parent body. This is very applicable to the FOWT and I haven't seen the implementation yet. This particular case is the combination of ship hull and a running propeller.

As a first step I just want to be sure that the sixDoF values are properly read inside my class, after I can get into the mathematics of proper updating. In essence, I have been following your implementation from actuatorLineSource.C and I am not getting the output correctly. As you can see from the output of the solver, the CoG value marked in red should be the same value as the centre of rotation from sixDoF.  I am also sending you the dynamicMeshDict, but is not that relevant I think.

[dynamicMeshDict.txt](https://github.com/fronterapp/thesis-FloatingTurbine/files/13456209/dynamicMeshDict.txt)

[lib_output.docx](https://github.com/fronterapp/thesis-FloatingTurbine/files/13456170/lib_output.docx)

Kind regards,

Ivan

p.s. if it would be necessary I will prepare some simple test case for you
