### ISSUE TITLE
A question about case/Chapter6

### ISSUE THREAD

**Issue by ZhouYmi** [fronterapp/thesis-FloatingTurbine#7]
![issue](https://github.com/user-attachments/assets/24f6325b-f560-4ffc-a655-459db0f88582)
Hi Pere， 
Sorry to bother you. When I using a command:  
mpirun --oversubscribe -np 8 pimpleFoam -parallel， 
to running SteadyL11a in Chapter 6, the following problem occurred. How should I solve this problem. 
Best regards, 
Zhou

**Comment by fronterapp** [comment]
Dear Zhou,

I'm sorry for not getting back to you sooner. It seems that the aerodynamic coefficient [tables ](https://github.com/fronterapp/thesis-FloatingTurbine/tree/main/cases/Chapter_6/OC6_III/resources/foilData) are given for 7 Reynolds numbers, but Re = 0 is missing in [fvOptions](https://github.com/fronterapp/thesis-FloatingTurbine/blob/main/cases/Chapter_6/OC6_III/steadyL11a/system/fvOptions). 

A quick fix would be to add a zero in the Reynolds list in fvOptions: `ReList (0.0E+00 5.0E+04 6.0E+04 7.5E+04 1.0E+05 1.5E+05 1.7E+05 2.0E+05);`

Let me know if that works out.

Best,
Pere

**Comment by ZhouYmi** [comment]
发自我的iPhone


------------------ Original ------------------
From: Pere Frontera ***@***.***&gt;
Date: Mon,Aug 19,2024 6:52 PM
To: fronterapp/thesis-FloatingTurbine ***@***.***&gt;
Cc: ZhouYmi ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [fronterapp/thesis-FloatingTurbine] A question aboutcase/Chapter6 (Issue #7)





 
Dear Zhou,
 
I'm sorry for not getting back to you sooner. It seems that the aerodynamic coefficient tables  are given for 7 Reynolds numbers, but Re = 0 is missing in fvOptions.
 
A quick fix would be to add a zero in the Reynolds list in fvOptions: ReList (0.0E+00 5.0E+04 6.0E+04 7.5E+04 1.0E+05 1.5E+05 1.7E+05 2.0E+05);
 
Let me know if that works out.
 
Best,
 Pere

**Comment by ZhouYmi** [comment]
Dear Pere,
Thank you for your reply and everything you done for this code. Since I used your code in Chapter 7 later, the code in Chapter 7 will not use Renold number, so I forgot this matter and only saw this reply today. I feel sorry for that. I will try the method you provided in the near future. Thank you again for your reply
Sincerely,
Zhou&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Pere Frontera ***@***.***&gt;
Date: Mon,Aug 19,2024 6:52 PM
To: fronterapp/thesis-FloatingTurbine ***@***.***&gt;
Cc: ZhouYmi ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [fronterapp/thesis-FloatingTurbine] A question aboutcase/Chapter6 (Issue #7)





 
Dear Zhou,
 
I'm sorry for not getting back to you sooner. It seems that the aerodynamic coefficient tables  are given for 7 Reynolds numbers, but Re = 0 is missing in fvOptions.
 
A quick fix would be to add a zero in the Reynolds list in fvOptions: ReList (0.0E+00 5.0E+04 6.0E+04 7.5E+04 1.0E+05 1.5E+05 1.7E+05 2.0E+05);
 
Let me know if that works out.
 
Best,
 Pere
