### ISSUE TITLE
Chapter_7 can't run in OpenFOAM2012

### ISSUE THREAD

**Issue by byChen47** [fronterapp/thesis-FloatingTurbine#8]
Dear @fronterapp ,
when after I wmake all libraries src,and  try to run the Chapter_7 couple case, it is show error, and can't no run successful,which seem the flaotngTurbinesFoam can't run 
I hope you can help me to slover the problem.

Best regard
chen

**Comment by fronterapp** [comment]
Dear Chen, could you explain the error in more detail?

**Comment by byChen47** [comment]
Dear @fronterapp ,
Thank you very much for replying to me so quickly.
When I finished compiling the two libraries on thesis-FloatingTurbine-main/libraries  in OpenFOAM 2012 ,and I want to run the Chapter_7/coupled,which show the error, I don't know the reason. the error message is show in error.txt. 
[error.txt](https://github.com/user-attachments/files/16658074/error.txt)

**Comment by byChen47** [comment]
Dear @fronterapp ,
Sorry to bother you, I re-run the cases of coupled , and I find it seem no problem, the previous error is just caused by me not following your program.And now I running the cases of coupled .

Thank you very much 
Best regard
chen
